config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "pages#home"

  resources :profiles do
    resources :visits, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/process_dom', to: 'vulgarities#process_dom'
      resources :users, only: [:index] do
        collection do
          patch :change_category
        end
      end

    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :visits, dependent: :destroy

  validates :nickname, :birth_date, presence: true
  has_one_attached :picture
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update destroy]

  def index
    @profiles = current_user.profiles
    @visits = current_user.visits
    if params[:child].present?
      @profile = @profiles.find(params[:child])
    else
      @profile = current_user.profiles.find_by(selected: true) || @profiles.first
    end
    # récupérer toutes les urls visités et mots changés pour l'ensemble des profils
    @today_profiles_visits = Visit.today.where(profile: @profiles)
    @today_words_changed = @today_profiles_visits.sum(&:words_changed)

    # pour les 7 derniers jours
    @last_seven_days_profiles_visits = Visit.week.where(profile: @profiles)
    @last_seven_days_words_changed = @last_seven_days_profiles_visits.sum(&:words_changed)


    # récupérer toutes les urls visités et mots changés pour un seul profil
    @today_profile_visits = @profile.visits.where("date >= ?", DateTime.current.beginning_of_day)
    @today_profile_words_changed = @today_profile_visits.sum(&:words_changed)

  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @category = Category.find(params[:profile][:category_id])
    @profile = Profile.new(params_profile)
    @profile.user = current_user
    @profile.category = @category

    if @profile.save
      redirect_to profiles_path
    else
      render :new, status: :unprocessable_entity, flash: { error: @profile.errors.full_messages }
    end

  end

  def edit
  end

  def update
    @profile.update(params_profile)
    redirect_to profiles_path, notice: "Votre profil a bien été modifié"
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path, notice: "Votre profil a bien été supprimé"
  end


  private

  def params_profile
    params.require(:profile).permit(:nickname, :birth_date, :picture, :category_id)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end
end

app/views/profiles/_card_profiles.html.erb
<div class="card-profil">

  <% @profiles.each do |profile| %>
    <div class="card <%= 'bordered' if profile.id.to_s == params[:child] %>" >
      <%= link_to request.params.merge(child: profile.id) do %>
        <div class= "card_int">
            <% if profile.picture.attached? %>
              <%= cl_image_tag(profile.picture.key, class: 'card_img') %>
            <% else %>
              <%= image_tag 'avatar_default.png', class: 'card_img' %>
            <% end %>
              <div class="card_name">
                  <strong><%= profile.nickname %></strong>
                  <%# <%= (Date.today - profile.birth_date).to_i / 365 %>
                <div class= "catego">
                  <%= profile.category.name %>
                </div>
              </div>
        </div>

        <span class="card_action">
          <%= link_to edit_profile_path(profile), class: "edit-button" do %>
            <i class="fa-solid fa-pen" style="color: #0d0c0c;"></i>
          <% end %>
        </span>
      <% end %>
    </div>
  <% end %>

  <div class="card-new-profile">
    <%= link_to new_profile_path, class:"add-button" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <% end %>
  </div>
</div>

app/views/profiles/_card_today.html.erb
  <div class="div1 card-hist">

    <div class="div-title">
      <p>Aujourd'hui</p>
    </div>

    <div class= "div-content">
        <%= render 'today_visits' %>
    </div>

  </div>

app/views/profiles/_card_urls.html.erb
 <div class="card-url">

    <div class="div-title">
      <p>Historique de navigation</p>
    </div>
        <%= render 'urls' %>
  </div>

app/views/profiles/_card_weeks.html.erb
  <div class="div2 card-hist">
    <div class="div-title">
      <p>Durant les 7 derniers jours</p>
    </div>

    <div class= "div-content">
        <%= render 'last_seven_days_visits' %>
    </div>
  </div>

app/views/profiles/_historics.html.erb
<ul>
  <% @profile.visits.last(15).reverse.each do |visit| %>
    <li>
      <a href="<%= visit.url %>" target="_blank" class="link-url">
      <span> site: <%= visit.title %></span>
      </a>
      ---
      <p>mots changés: <%= visit.words_changed %></p>
      ---
      <span> le : <%= visit.date.strftime("%d/%m/%Y à %H:%M") %></span>
    </li>

      <% end %>
</ul>


  <%# <span> il y a <%= (Date.today - visit.date).to_i </span> %>

app/views/profiles/_last_seven_days_visits.html.erb
<ul>
  <% @profiles.each do |profile| %>
    <li>
      <div>
        <%= profile.nickname %> :
      </div>
      <div style='font-size: 1.3em;'>
        <%= profile.visits.week.sum(&:words_changed) %> mots
      </div>
    </li>
  <% end %>
</ul>

app/views/profiles/_today_visits.html.erb
<ul>
   <% @profiles.each do |profile| %>
    <li>
      <div>
        <%= profile.nickname %>
      </div>
      <div style='font-size: 1.3em;'>
        <%= profile.visits.today.sum(&:words_changed) %> mots
      </div>
    </li>
   <% end %>
</ul>

app/views/profiles/_urls.html.erb
<div class="url-list">


    <p class="left" id="bottomline">Sites visités</p>
    <p class="right">Mots détectés</p>
    <p class="right">Date</p>


  <% @profile.visits.last(15).reverse.each do |visit| %>

      <div class="url-title left">
        <a href="<%= visit.url %>" target="_blank" class="link-url">
        <%= visit.title %>
        </a>
      </div>

      <div class="url-words right">
        <div class="url-words right">
        <%= visit.words_changed %>
          <% if visit.words_changed <= 1 %>
            mot
          <% else %>
            mots
          <% end %>
        </div>
      </div>

      <div class="url-date right">
        <%= visit.date.strftime("%d/%m - %H:%M") %>
      </div>

  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class= 'container'>
  <div class= 'row'>
    <div class= 'column'>
      <h2>Modifier ce profil</h2>
        <%= simple_form_for @profile do |f| %>
        <%= f.error_notification %>

          <div class="form-inputs">

            <%= f.input :nickname, label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "nickname" }%>
            <%= f.input :picture, as: :file,
                label: "Photo de profil",
                required: false,
                input_html: { autocomplete: "picture" } %>
            <%= f.input :birth_date, :as => :date, label: 'Date de naissance',
                start_year: Date.today.year,
                end_year: Date.today.year - 18,
                order: [:day, :month, :year] %>
            <%= f.input :category_id, label: "Niveau de sécurité",
                collection: Category.pluck(:name, :id) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Mettre à jour" %>
          </div>
        <% end %>
        <%= link_to "Supprimer ce profil", profile_path(@profile), data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr?'} %>
        <%= link_to "Retour", :back %>

    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="flex-container">
  <div class="main">

    <%= render "shared/navbar" %>

    <div class="parent">

      <div class="div1">
        <%= render 'card_today' %>
      </div>

      <div class="div2">
        <%= render 'card_weeks' %>
      </div>

      <div class="div4">
        <%= render 'card_urls' %>
      </div>
    </div>
  </div>

  <div class="profils">
    <h4>Profils</h4>
    <%= render 'card_profiles' %>
  </div>
</div>

<%# <!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<%# <% content_for :meta_description, @offer.description %>
<%# <% content_for :meta_image, cl_image_path(@offer.photo.path) %>

app/views/profiles/new.html.erb
<div class= 'container'>
  <div class= 'row'>
    <div class= 'column'>
      <h2>Ajouter un profil</h2>
        <%= simple_form_for @profile do |f| %>
        <%= f.error_notification %>

          <div class="form-inputs">

            <%= f.input :nickname, label: 'Nom',
                required: true,
                autofocus: true,
                input_html: { autocomplete: "nickname" }%>
            <%= f.input :birth_date, :as => :date, label: 'Date de naissance',
                start_year: Date.today.year,
                end_year: Date.today.year - 12,
                order: [:day, :month, :year] %>
            <%= f.input :picture, as: :file,
                label: "Photo de profil",
                required: false,
                input_html: { autocomplete: "picture" } %>
            <%= f.input :category_id, label: "Niveau de sécurité",
                collection: Category.pluck(:name, :id) %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Enregistrer" %>
          </div>
        <% end %>
        <%= link_to "Supprimer ce profil", profiles_path %>
        <%= link_to "Retour", :back %>

    </div>
  </div>
</div>