config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "pages#home"

  resources :profiles do
    resources :visits, only: [:index, :show]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/process_dom', to: 'vulgarities#process_dom'
      resources :users, only: [:index] do
        collection do
          patch :change_category
        end
      end

    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# code yo  %>
<%# <div class="footer hidden">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    <span>© All rights reserved for Pixy - 2023</span>
  </div>
</div> %>






 <%# code elise %>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
    <span>© All rights reserved for Pixy - 2023</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div>
         <h5>Pixy</h5>
        <h2>Bienvenue <%= current_user.first_name %>,<br> consultez votre espace personnel :</h2>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag(current_user.avatar.key, class: "avatar-round", alt: "dropdown menu") %>
          <% else %>
            <%= image_tag "https://static.thenounproject.com/png/5034901-200.png", class: "avatar", alt: "dropdown menu" %>
          <% end %>

          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon compte", profiles_path, class: "dropdown-item" %>
              <%= link_to "Modif. compte", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Retour à l'acceuil", root_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "S'identifier", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>